# k8s_job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: file-download-job
spec:
  template:
    spec:
      containers:
      - name: downloader
        image: gcr.io/your-project/downloader:latest
      restartPolicy: OnFailure
